version: 2.1

# Configuración de la imagen de entorno de la máquina
# Puedes especificar una imagen de contenedor personalizada si es necesario
image: macos-latest

# Definición de los trabajos de construcción y las configuraciones
workflows:
  ios-build:
    name: iOS Build Workflow
    max_build_duration: 60 # minutos
    triggers:
      # Ejecutar el flujo de trabajo en cada push a la rama 'main'
      - schedule:
          cron: "0 0 * * *" # cada día a medianoche
          filters:
            branches:
              only:
                - main
    jobs:
      - name: Install Dependencies
        script:
          - flutter pub get
          - flutter doctor
          - gem install cocoapods # Instala CocoaPods si no está ya instalado

      - name: Build iOS App
        script:
          # Ejecutar el build para iOS
          - flutter build ios --release --no-codesign

      - name: Archive and Export iOS App
        script:
          # Archivar y exportar el archivo .ipa
          - cd ios
          - pod install
          - cd ..
          - xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $HOME/Runner.xcarchive
          - xcodebuild -exportArchive -archivePath $HOME/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath $HOME/ipa
          
      - name: Upload to App Store Connect (Optional)
        script:
          # Solo si necesitas subir a App Store Connect
          - gem install fastlane
          - fastlane deliver --ipa $HOME/ipa/Runner.ipa --skip_screenshots --skip_metadata

    artifacts:
      - $HOME/ipa/*.ipa # Artifacts para descargar después de la build
      - $HOME/Runner.xcarchive # Archivos de archivo (opcional)

# Configuración para notificaciones y otros ajustes
notifications:
  email:
    recipients:
      - your-email@example.com
    on_success: never
    on_failure: always
