version: 2.1

workflows:
  ios-build:
    name: Build and Archive iOS App
    max_build_duration: 60 # minutos
    environment:
      flutter: stable
      xcode: latest
      cocoapods: stable
    steps:
      - name: Install Dependencies
        run: |
          flutter pub get
          flutter doctor
          gem install cocoapods

      - name: Build iOS App
        run: |
          flutter build ios --release --no-codesign

      - name: Archive iOS App
        run: |
          cd ios
          pod install
          cd ..
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $HOME/Runner.xcarchive
          xcodebuild -exportArchive -archivePath $HOME/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath $HOME/ipa

    artifacts:
      - $HOME/ipa/*.ipa
      - $HOME/Runner.xcarchive
