workflows:
  agenda-app:
    name: agenda de citas
    instance_type: mac_mini_m1
    max_build_duration: 60
    inputs: # more information about build inputs:https://docs.codemagic.io/knowledge-codemagic/build-inputs/
      name: # input ID
        description: Input description
        default: Codemagic
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - echo "Hello, ${{ inputs.name }}"
    artifacts:
      - build/ios/ipa/MyApp.ipa
      - build/ios/simulator/MyApp.app
      - build/macos/Build/Products/Release/MyApp.app
      - build/ios/outputs/bundle/agenda.aab
    publishing:
      email:
        recipients:
          - luguidu77@gmail.com
      scripts:
        - echo 'Post-publish script'