// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ryhTNEb2zpMKrFZiMsIAyasbK0gYrMA',
    appId: '1:669231682418:web:1830cd6b8203d03bd7c3eb',
    messagingSenderId: '669231682418',
    projectId: 'flutter-varios-576e6',
    authDomain: 'flutter-varios-576e6.firebaseapp.com',
    databaseURL: 'https://flutter-varios-576e6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-varios-576e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbR2Fm8mMy9be3VGyZ0_rI7C715uBMos0',
    appId: '1:669231682418:android:4d53e97fb4fc8f6bd7c3eb',
    messagingSenderId: '669231682418',
    projectId: 'flutter-varios-576e6',
    databaseURL: 'https://flutter-varios-576e6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-varios-576e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLrPjCtrfOcjJTBvaqVzNbTnnezcMEPBQ',
    appId: '1:669231682418:ios:fd5a3e57b6230461d7c3eb',
    messagingSenderId: '669231682418',
    projectId: 'flutter-varios-576e6',
    databaseURL: 'https://flutter-varios-576e6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-varios-576e6.appspot.com',
    iosClientId: '669231682418-p9o4orcsj9kemcarupol383f2nad3c7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendacitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLrPjCtrfOcjJTBvaqVzNbTnnezcMEPBQ',
    appId: '1:669231682418:ios:6852f3d13d9db239d7c3eb',
    messagingSenderId: '669231682418',
    projectId: 'flutter-varios-576e6',
    databaseURL: 'https://flutter-varios-576e6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-varios-576e6.appspot.com',
    iosClientId: '669231682418-hu1rs884ve5po6ioogdiscdpq3u5d93b.apps.googleusercontent.com',
    iosBundleId: 'agendadecitas.app.agendadecitas',
  );
}
